### ISSUE TITLE
Apex import Causes ' cannot import name 'container_abcs' '

### ISSUE THREAD

**Issue by midhunharikumar** [NVIDIA/apex#186]
I'm trying to import apex after installing from source. I have pytorch version 0.4.1. I used the `pip install -v --no-cache-dir  .`   and received this stack trace when i import.

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/deploy/apex/apex/__init__.py", line 2, in <module>
    from . import amp
  File "/deploy/apex/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/deploy/apex/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/deploy/apex/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/deploy/apex/apex/amp/_initialize.py", line 2, in <module>
    from torch._six import container_abcs, string_classes
ImportError: cannot import name 'container_abcs`

**Comment by mcarilli** [comment]
I'll look into a backward compatibility fix.  In the meantime, we recommend Pytorch 1.0 or later.  If you don't want to install pytorch on bare metal, you can try one of the supported Docker containers (https://github.com/NVIDIA/apex/issues/112#issuecomment-453307010).

**Comment by midhunharikumar** [comment]
> I'll look into a backward compatibility fix. In the meantime, we recommend Pytorch 1.0 or later. If you don't want to install pytorch on bare metal, you can try one of the supported Docker containers ([#112 (comment)](https://github.com/NVIDIA/apex/issues/112#issuecomment-453307010)).

Will try this. I'm working with an older package that does not seem to like pytorch 1.0

**Comment by midhunharikumar** [comment]
Any updates on this ? I'm currently working with an older commit without any of the new optimizations .

**Comment by matanhs** [comment]
just open apex/amp/_initialize.py and replace the command `from torch._six import container_abcs` with  `import collections.abc as container_abcs` (for python 3) works for me with pytorch 0.41

**Comment by mcarilli** [comment]
I pushed a fix for this, but I still recommend you move to pytorch 1.0 or later, it's much more stable in general.

**Comment by Maddy12** [comment]
I am with all up to date PyTorch and PyTorch Lightning, still having this same issue

**Comment by qanastek** [comment]
> I am with all up to date PyTorch and PyTorch Lightning, still having this same issue

Any improvements since then ? I am experiencing the same issues too since a week.

**Comment by AlexandrParkhomenko** [comment]
> just open apex/amp/_initialize.py and replace the command `from torch._six import container_abcs` with `import collections.abc as container_abcs` (for python 3) works for me with pytorch 0.41

it helps in https://github.com/snap-stanford/GraphGym

**Comment by ludwigwittgenstein2** [comment]
> > just open apex/amp/_initialize.py and replace the command `from torch._six import container_abcs` with `import collections.abc as container_abcs` (for python 3) works for me with pytorch 0.41
> 
> it helps in https://github.com/snap-stanford/GraphGym

Can't do that in colab
